language: python

python:
  - "3.5"

sudo: required

services:
  - docker

install: "pip install -r requirements.txt"

env:
  - ANDROID_VERSION=5.0.1
  - ANDROID_VERSION=5.1.1
  - ANDROID_VERSION=6.0
  - ANDROID_VERSION=7.0
  - ANDROID_VERSION=7.1.1
  - REAL_DEVICE=True

script: bash travis.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
